### ISSUE TITLE
Test failure testGeoRectIntersect(com.spatial4j.core.shape.ShapeCollectionTest)

### ISSUE THREAD

**Issue by dsmiley** [locationtech/spatial4j#113]
testGeoRectIntersect(com.spatial4j.core.shape.ShapeCollectionTest)  Time elapsed: 1.207 sec  <<< FAILURE!
java.lang.AssertionError: Rect(minX=-70.0,maxX=-24.0,minY=-66.0,maxY=-18.0) intersect Pt(x=46.86357190711945,y=-29.539922296850065)
        at __randomizedtesting.SeedInfo.seed([A1208F48E493C664:82971F9D6553947B]:0)
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at com.spatial4j.core.shape.RandomizedShapeTest._assertIntersect(RandomizedShapeTest.java:161)
        at com.spatial4j.core.shape.RandomizedShapeTest.assertRelation(RandomizedShapeTest.java:146)
        at com.spatial4j.core.shape.RectIntersectionTestHelper.testRelateWithRectangle(RectIntersectionTestHelper.java:82)
        at com.spatial4j.core.shape.ShapeCollectionTest.testGeoRectIntersect(ShapeCollectionTest.java:71)

**Comment by dsmiley** [comment]
Possible repeat:  7F635E3C80EDA9DB:5CD4CEE9012DFBC4
