### ISSUE TITLE
Serializing a list of MultiPoint geometry with jackson throws a JsonGenerationException

### ISSUE THREAD

**Issue by PapaStan** [locationtech/spatial4j#210]
Hi,

I went into an error when serializing a list of MultiPoint geometry with jackson.
It seems like the jackson generator context has been changed by the `GeometryAsGeoJSONSerializer` and not set back.

You can reproduce by running the following:

```java
import java.util.List;

import org.locationtech.jts.geom.Coordinate;
import org.locationtech.jts.geom.GeometryFactory;
import org.locationtech.jts.geom.MultiPoint;
import org.locationtech.jts.geom.Point;
import org.locationtech.spatial4j.io.jackson.ShapesAsGeoJSONModule;

import com.fasterxml.jackson.databind.ObjectMapper;

public class Main {

    public static void main(String[] args) throws Exception {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new ShapesAsGeoJSONModule());

        GeometryFactory geometryFactory = new GeometryFactory();

        Point point = geometryFactory.createPoint(new Coordinate(100, 100));
        MultiPoint multiPoint = geometryFactory.createMultiPoint(new Point[] { point });
        System.out.println(objectMapper.writeValueAsString(List.of(point)));
        System.out.println(objectMapper.writeValueAsString(List.of(multiPoint)));
    }

}
```

It leads to the following output:
```
[{"type":"Point","coordinates":[100.0,100.0]}]
Exception in thread "main" com.fasterxml.jackson.core.JsonGenerationException: Current context not Array but Object
        at com.fasterxml.jackson.core.JsonGenerator._reportError(JsonGenerator.java:2657)
        at com.fasterxml.jackson.core.json.WriterBasedJsonGenerator.writeEndArray(WriterBasedJsonGenerator.java:295)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:80)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4487)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3742)
        at Main.main(Main.java:22)
```

The fix seems quite simple: https://github.com/PapaStan/spatial4j/commit/142d3f88ad05a79319ebda8385a00920ffbd9582

**Comment by dsmiley** [comment]
Thanks for reporting this.  Wow; that bug just stands out there -- the only return statement when all the other branches don't.  PR welcome!
