### ISSUE TITLE
Need to wrap with JTS TopologyException with InvalidShapeException

### ISSUE THREAD

**Issue by dsmiley** [locationtech/spatial4j#30]
Need to wrap with TopologyException with InvalidShapeException, probably within JtsGeometry constructor

com.vividsolutions.jts.geom.TopologyException: found non-noded intersection between LINESTRING ( 350.13064515844655 -70.90020898221194, 394.1403541994338 -68.48279097996054 ) and LINESTRING ( 428.9364182318401 -72.424999983632, 134.4378362928431 -64.92613597664814 ) [ (356.1244099533009, -70.57097629169705, NaN) ]
    at com.vividsolutions.jts.noding.FastNodingValidator.checkValid(FastNodingValidator.java:126)
    at com.vividsolutions.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:94)
    at com.vividsolutions.jts.geomgraph.EdgeNodingValidator.checkValid(EdgeNodingValidator.java:59)
    at com.vividsolutions.jts.operation.overlay.OverlayOp.computeOverlay(OverlayOp.java:170)
    at com.vividsolutions.jts.operation.overlay.OverlayOp.getResultGeometry(OverlayOp.java:127)
    at com.vividsolutions.jts.operation.overlay.OverlayOp.overlayOp(OverlayOp.java:66)
    at com.vividsolutions.jts.operation.overlay.snap.SnapIfNeededOverlayOp.getResultGeometry(SnapIfNeededOverlayOp.java:62)
    at com.vividsolutions.jts.operation.overlay.snap.SnapIfNeededOverlayOp.overlayOp(SnapIfNeededOverlayOp.java:25)
    at com.vividsolutions.jts.geom.Geometry.union(Geometry.java:1361)
    at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionActual(CascadedPolygonUnion.java:369)
    at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionOptimized(CascadedPolygonUnion.java:293)
    at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionSafe(CascadedPolygonUnion.java:274)
    at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.binaryUnion(CascadedPolygonUnion.java:212)
    at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.binaryUnion(CascadedPolygonUnion.java:218)
    at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.binaryUnion(CascadedPolygonUnion.java:193)
    at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionTree(CascadedPolygonUnion.java:139)
    at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.reduceToGeometries(CascadedPolygonUnion.java:243)
    at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionTree(CascadedPolygonUnion.java:137)
    at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.reduceToGeometries(CascadedPolygonUnion.java:243)
    at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionTree(CascadedPolygonUnion.java:137)
    at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.reduceToGeometries(CascadedPolygonUnion.java:243)
    at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.unionTree(CascadedPolygonUnion.java:137)
    at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.union(CascadedPolygonUnion.java:127)
    at com.vividsolutions.jts.operation.union.CascadedPolygonUnion.union(CascadedPolygonUnion.java:73)
    at com.vividsolutions.jts.operation.union.UnaryUnionOp.union(UnaryUnionOp.java:174)
    at com.vividsolutions.jts.operation.union.UnaryUnionOp.union(UnaryUnionOp.java:93)
    at com.vividsolutions.jts.geom.Geometry.union(Geometry.java:1435)
    at com.spatial4j.core.shape.jts.JtsGeometry.unionGeometryCollection(JtsGeometry.java:334)
    at com.spatial4j.core.shape.jts.JtsGeometry.<init>(JtsGeometry.java:58)
    at com.spatial4j.core.io.JtsShapeReadWriter.readShape(JtsShapeReadWriter.java:93)
    at com.spatial4j.core.context.SpatialContext.readShape(SpatialContext.java:195)

**Comment by carlos-verdes** [comment]
Hi @dsmiley , 
We need in our project to reproduce a TopologyException in union and intersection operations to handle the error with a different geom approach (like using a buffer). Could you give to us in WKT two geometries that force a TopologyException when doing intersection or union? 
Thanks in advance!!

**Comment by dsmiley** [comment]
I see you got a sample from asking on the JTS mailing list.  W.R.T. Spatial4j, Spatial4j can be configured to automatically apply one of a couple strategies of your choice, and this is configured in the JtsSpatialContextFactory.
