### ISSUE TITLE
is there a class by name Lineal in vividsolutions geom?

### ISSUE THREAD

**Issue by vanng822** [locationtech/spatial4j#78]
I am not a java developer and also not sure where to report this issue.

I run solr 4.7.1 with polygon search feature and when I do a polygon search I got this class not found exception

Caused by: java.lang.NoClassDefFoundError: com/vividsolutions/jts/geom/Lineal
    at com.spatial4j.core.shape.jts.JtsGeometry.<init>(JtsGeometry.java:104)

I scans for this class in com/vividsolutions/jts (from version 1.8 to 1.5) but can not find any class by this name. Do I miss something or this is a bug?
## Some more trace

Caused by: java.lang.NoClassDefFoundError: com/vividsolutions/jts/geom/Lineal
    at com.spatial4j.core.shape.jts.JtsGeometry.<init>(JtsGeometry.java:104)
    at com.spatial4j.core.context.jts.JtsSpatialContext.makeShape(JtsSpatialContext.java:203)
    at com.spatial4j.core.io.jts.JtsWktShapeParser.makeShapeFromGeometry(JtsWktShapeParser.java:252)
    at com.spatial4j.core.io.jts.JtsWktShapeParser.parsePolygonShape(JtsWktShapeParser.java:133)
    at com.spatial4j.core.io.jts.JtsWktShapeParser.parseShapeByType(JtsWktShapeParser.java:89)
    at com.spatial4j.core.io.WktShapeParser.parseIfSupported(WktShapeParser.java:114)
    at com.spatial4j.core.io.WktShapeParser.parse(WktShapeParser.java:86)
    at com.spatial4j.core.context.SpatialContext.readShapeFromWkt(SpatialContext.java:294)
    at org.apache.solr.schema.AbstractSpatialFieldType.parseShape(AbstractSpatialFieldType.java:170)
    at org.apache.solr.schema.AbstractSpatialFieldType$1.parseShape(AbstractSpatialFieldType.java:117)
    at org.apache.lucene.spatial.query.SpatialArgsParser.parse(SpatialArgsParser.java:90)
    at org.apache.solr.schema.AbstractSpatialFieldType.parseSpatialArgs(AbstractSpatialFieldType.java:253)
    at org.apache.solr.schema.AbstractSpatialFieldType.getFieldQuery(AbstractSpatialFieldType.java:248)
    at org.apache.solr.parser.SolrQueryParserBase.getFieldQuery(SolrQueryParserBase.java:738)
    at org.apache.solr.parser.SolrQueryParserBase.getFieldQuery(SolrQueryParserBase.java:388)
    at org.apache.solr.parser.SolrQueryParserBase.handleQuotedTerm(SolrQueryParserBase.java:556)
    at org.apache.solr.parser.QueryParser.Term(QueryParser.java:403)
    at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:185)
    at org.apache.solr.parser.QueryParser.Query(QueryParser.java:107)
    at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:96)
    at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:152)
    at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:50)
    at org.apache.solr.search.QParser.getQuery(QParser.java:141)
    at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:170)
    at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:196)
    at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)
    at org.apache.solr.core.SolrCore.execute(SolrCore.java:1916)
    at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:780)
    at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:427)

**Comment by jpalbuja** [comment]
Hi guys, from where did you downloaded the JTS library? I am experimenting the same thing with 1.8. Thanks

**Comment by dsmiley** [comment]
I usually get my Java libs via Maven.

http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.vividsolutions%22%20AND%20a%3A%22jts%22
